### ISSUE TITLE
drag 'n drop is erratic

### ISSUE THREAD

**Issue by domichel** [alsaplayer/alsaplayer#5]
When dropping multiple files from thunar and rox-filler into alsaplayer playlist window, the result is erratic.

A few times all files get into the playlist, but most of the time, some files are missing. From a mail I get, it is even possible that the entire parenting folder and it's entire contents will be added.

Also, the order of the files with drag'n drop is erratic into the playlist.

**Comment by domichel** [comment]
I retested that. In both 1. and 2. it is with multiple files or directories and well, gtk+ 2.24.33.

With 11 flac files, a m3u file, 2 jpeg, a cue and a log file:
  1) if I drag n drop the directory, I get all the files but the order is crewed.
  2) with the m3u file, I get all the files and their order is correct.
  3) with all the files or all the flac files only, I get the 4 first files and their order is correct.

With another directory, 12 flac files and 3 jpeg files, 1) and 3) behave the same, but I get only 3 files on 12 with 3).

With a directory with 8 mp3 files and 6jpg file, 1) behave the same and with 2) the good news is than it didn't crashed.
  2) It took a while and I get a playlist with only 4 files on that directory, but 17710 entries in total. It look like AP scanned my whole home directory. In these entries, it is a lot of audio files, inclusive Amiga mod files, a .MODULES_res and a .OUTMOD files, and even .xml files. And ~/.Xmodmap too. Some files in .git 'modules' directories... and a lot of random files with a modules directory in their PATH.

Which imply I get at least 3 bad symptoms:
1) The order of the files can get screwed.
2) AP can scan everything in $HOME.
3) AP consider than a file *mod* or a /*/*mod*/*/file are a mod files.

**Comment by domichel** [comment]
[consoleoutput.txt](https://github.com/alsaplayer/alsaplayer/files/14945659/consoleoutput.txt)
[alsaplayer.m3u.txt](https://github.com/alsaplayer/alsaplayer/files/14945664/alsaplayer.m3u.txt)

**Comment by domichel** [comment]
The directory with the files https://file.io/sRIJv9FFK1dD
Its full PATH is ~/Musique/Ange -mp3/1974 - Au delà du délire

**Comment by domichel** [comment]
I put these files here : 
https://github.com/alsaplayer/test/tree/main/drag_n_drop

**Comment by domichel** [comment]
I got a strace output, but I don't even understand if it can be useful:
[straceout.txt](https://github.com/alsaplayer/alsaplayer/files/14951975/straceout.txt)

**Comment by domichel** [comment]
I try to do that https://wiki.gentoo.org/wiki/UndefinedBehaviorSanitizer
It is to enable -g -fsanitize=undefined 
```
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1" alsaplayer
mad_engine.c:432:30: runtime error: left shift of negative value -113
    #0 0x7f6a61b4e364 in from_synchsafe4 /usr/src/debug/media-sound/alsaplayer-9999/alsaplayer-9999/input/mad/mad_engine.c:432
    #1 0x7f6a61b54f7b in parse_id3 /usr/src/debug/media-sound/alsaplayer-9999/alsaplayer-9999/input/mad/mad_engine.c:610
    #2 0x7f6a61b54f7b in mad_stream_info /usr/src/debug/media-sound/alsaplayer-9999/alsaplayer-9999/input/mad/mad_engine.c:794
    #3 0x7f6a61b54f7b in mad_stream_info /usr/src/debug/media-sound/alsaplayer-9999/alsaplayer-9999/input/mad/mad_engine.c:777
    #4 0x564dd41a99d4 in CorePlayer::GetStreamInfo(_stream_info*) /usr/src/debug/media-sound/alsaplayer-9999/alsaplayer-9999/app/CorePlayer.cpp:547
    #5 0x564dd41c2e28 in info_looper(Playlist*) /usr/src/debug/media-sound/alsaplayer-9999/alsaplayer-9999/app/Playlist.cpp:208
    #6 0x564dd41d45cf in insert_looper(void*) /usr/src/debug/media-sound/alsaplayer-9999/alsaplayer-9999/app/Playlist.cpp:393
    #7 0x564dd4209780 in Playlist::Insert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) ../alsaplayer/Playlist.h:270
    #8 0x564dd4206358 in socket_looper /usr/src/debug/media-sound/alsaplayer-9999/alsaplayer-9999/app/ControlSocket.cpp:174
    #9 0x7f6a61e5eb6b  (/lib64/libc.so.6+0x86b6b)
    #10 0x7f6a61edf757  (/lib64/libc.so.6+0x107757)

```

**Comment by domichel** [comment]
When using portage to install the last git code, I get:
```
>>> Installing (1 of 1) media-sound/alsaplayer-9999::test
 * CMP: =media-sound/alsaplayer-9999 with media-sound/alsaplayer-9999/image
 *    ABI: libgtk2_interface.so(64) func(-2) [BREAKING]
 *   SIZE: 14.36MiB -> 1.40MiB, 51 -> 51 files
 * ------> ABI(-2,>B<) SIZE(-90.21%)
```
